# Generated by Django 5.0.6 on 2024-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Выполнено/В работе')),
                ('title', models.CharField(default='Заголовок', max_length=100, verbose_name='Заголовок задачи')),
                ('description', models.TextField(verbose_name='Постановка задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='Срок выполения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
