# Generated by Django 5.0.6 on 2024-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='status',
        ),
        migrations.AddField(
            model_name='todotask',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todos.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполения'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.TextField(default='Постановка задачи', verbose_name='Постановка задачи'),
        ),
    ]
